apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: paedelman-net-tls
spec:
  secretName: paedelman-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: paedelman.net
  dnsNames:
    - paedelman.net
    - www.paedelman.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - paedelman.net
          - www.paedelman.net